### ISSUE TITLE
i want to know Host or client

### ISSUE THREAD

**Issue by HarryHaiVn** [flutterjanus/flutter_janus_client#108]
i want to know, when i call , and join a meeting, who is the host, who is the guest, please help me. thanks

**Comment by shivanshtalwar** [comment]
That's upto you to implement because janus is general purpose webrtc server you might wana wrap janus server behind your own application server with proper database setup so you can know from the application who is creating the room and marking that user as host and others as client either way this is not the place nor the project to ask such questions please refrain from opening issues for questions, i suggest you ask these questions on meetecho google group
