### ISSUE TITLE
I can't add param in StreamRenderer

### ISSUE THREAD

**Issue by svn-nguyen-minh-hai** [flutterjanus/flutter_janus_client#109]
I want to know which user the video sharing belongs to. so I add 1 param to the StreamRenderer, with the value being the id of the video stream. but when I switch to another machine, I don't get that value, other params like publisherName,publisherId.. also don't exist, please tell me how to know which user the video sharing belongs to. thanks

**Comment by shivanshtalwar** [comment]
Source of truth about whose stream particular feed is can be derived from publisherHandle whenever there's event about existing publishers or new publishers joining the room we just need to update streamrenderer display property accordingly in the next update you can expect displayName support aswell otherwise i encourage you to try it on your own and if successfully do a pr of the same to keep this project going fast
Regards.
Shivansh

**Comment by svn-nguyen-minh-hai** [comment]
@shivanshtalwar I don't quite understand, can you be more specific?

**Comment by svn-nguyen-minh-hai** [comment]
@shivanshtalwar i want to distinguish normal video into screen sharing video. can you help

**Comment by shivanshtalwar** [comment]
@svn-nguyen-minh-hai i added support for displayName in google-meet example
