### ISSUE TITLE
Keep in background audio

### ISSUE THREAD

**Issue by jacopobonomi** [flutterjanus/flutter_janus_client#123]
Hi, thanks a lot for works on this project, it's really awesome!
I'm developing an app to get stream from Janus, one to many, server to client. All works great, but i have a problem to keep audio on in backgroung, in iOS and Android. After 30s-1m audio service ends.
Log message 
`[BackgroundTask] Background Task 175 ("Flutter debug task"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.`

Any idea to avoid this?

**Comment by shivanshtalwar0** [comment]
Well you need to run a foreground service as far as i know in Android you can't have background service without starting app with service in foreground for ios same needs to happen you probably have to research on that
Since this operation is beyond the scope of this project i will be closing this one, if you find any other issue feel free to open new one.
