### ISSUE TITLE
Use of part of, should be avoided

### ISSUE THREAD

**Issue by UserSense** [flutterjanus/flutter_janus_client#53]
Although this construction is present in the Dart language, it is not recommended for linking/importing files within the same library.

Also, it does not allow intellisense to check properly, potentially resulting in poorer code.

part of is actually nothing more than a placeholder construction, equivalent to putting everything in one file. 

https://dart.dev/guides/libraries/create-library-packages

I guess should restructure according to the guidline.

A big advantage is that a developer using the plugin will only have to include the code regaring the janus plugin it is using. Resulting in a smaller appsize. Currently all janus plugins are included.

This potential breaking for current implementations. So propably something for a next major version.

**Comment by shivanshtalwar0** [comment]
this isn't that big library and  earlier version of this library was written with export and imports but that  architecture of api split across multiple files was having serious drawbacks of private properties non accessible in composition of instances across different classes in different files which made me rewrite it using `part of` and in my opinion its not going away any time soon since many initial libraries still follow this architecture and for a good reason, if in future they deprecate part of then they will surely introduce alternative keyword something like `friend of` and then we will migrate the code accordingly.

**Comment by shivanshtalwar0** [comment]
with part of we have better control at what we expose as an api.

**Comment by UserSense** [comment]
Valid arguments to leave it as is.
