### ISSUE TITLE
can not listen to any event when join as subscriber

### ISSUE THREAD

**Issue by muhammadCodeSh** [flutterjanus/flutter_janus_client#88]
I get participants list and then join as a subscriber to the video room, at first everything is ok, but I can not listen to any event when a publisher leave room or join a new publisher,
I called every listener in JanusVideoRoomPlugin class but None of them worked.
please guide me

**Comment by shivanshtalwar0** [comment]
Kindly refer to documentation of janus for better understanding of how subscribers work in janus server as i am quoting from documentation
" In fact, the typical use case is publishers being notified about new participants becoming active in the room, and as a result new subscriber sessions being created to receive their media streams; as soon as the publisher goes away, other participants are notified so that the related subscriber handles can be removed/updated accordingly as well. As such, these subscriber sessions are dependent on feedback obtained by publishers, and can't exist on their own, unless you feed them the right info out of band (which is impossible in rooms configured with require_pvtid)."
https://janus.conf.meetecho.com/docs/videoroom.html
